config/routes.rb
Rails.application.routes.draw do
  get 'blog/index' => 'blog#index'

  get 'pages/home' => 'pages#home'
 
  
  root to: 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  helper_method :mesice
  PAGE_SIZE = 5

  def index
    @myClient           = Tumblr::Client.new(
    :consumer_key       => Rails.application.secrets.tumblr_key,
    :consumer_secret    => Rails.application.secrets.tumblr_secret,
    :oauth_token        => Rails.application.secrets.tumblr_oauth_token,
    :oauth_token_secret => Rails.application.secrets.tumblr_oauth_token_secret
    )
    
    #vitezslav.drobny@gmail.com
    #terassa2014

    page = params[:page].to_i
    if page == 0
      page = 1
    end

    @allposts = Array.new

    @posts = @myClient.posts("terassacasebistro.tumblr.com", limit: PAGE_SIZE, offset: PAGE_SIZE * (page-1) )

    @posts["posts"].each_index do |i|
      @allposts[(page-1)*PAGE_SIZE+i] = @posts["posts"][i]
    end

    total_posts = @posts["total_posts"]

    @allposts = Kaminari.paginate_array(@allposts, total_count: total_posts).page(page).per(PAGE_SIZE)
    puts @allposts

  end #end index

  private

   M_ARR = ["nil","leden", "únor", "březen", "duben", "květen", "červen", "červenec", "srpen", "září", "říjen", "listopad", "prosinec"];
  def mesice(m)
    M_ARR[m]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/index.html.erb
<% content_for :title do %>
Aktuálně
<% end %>

<div class="container">

  <div class="starter-template">
   
    <div class="test blog" >
      <h1>
        <span>Aktuálně</span>
      </h1>
      
    <% @allposts.each do |post| %>
    	<div class="ppost">
    	<% dt = DateTime.parse(post["date"]) %>
    		<h2 style="text-align:center">
    		<%= dt.day %>.
    		<%= dt.month %>.
    		<%= dt.year %>
    		</h3>
    		<% if post["type"] == "photo" %>
    			<%= image_tag post["photos"][0]["original_size"]["url"] %></p>
    			<%= simple_format( post["caption"])%></p>
    		<% else %>
    			<h3><%=  post["title"]  %></h3>
    			<%= simple_format(  post["body"] ) %>
    		<% end %>
    	</div>
    	<% end %>


    	<div class="pn">
    	<%= link_to_previous_page @allposts, 'Předchozí' %>

    	<%= link_to_next_page @allposts, 'Další' %>
    	</div>
      
     <h2 class="logo_down">
          <span><span></span></span>
      </h2>
      
	   
    
    
    
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" >
	<div class="container">
		
		
		<div class="col-md-12">
	       <%= link_to "Lucie Kepplová", "http://www.luciekepplova.cz/" %><span><%= link_to "JEDEMEDOBARU.CZ", "http://jedemedobaru.cz/" %></span><%= link_to "Adam Plánský", "http://www.adamplansky.cz/" %>
		</div>
		
	</div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%# link_to 'Home', root_path, class: 'navbar-brand' %>
        <a href="/" class="navbar-brand-col">
          <%= image_tag 'logo_menu_x2.png' %>
        </a>
    </div>
    
     
    <div class="collapse navbar-collapse">
      <div class="col-sm-5">
        <ul class="nav nav-justified menu-links navbar-left">
          <%= render 'layouts/navigation_links_left' %>
        </ul>
      </div>
      <div class="col-sm-2">
     <a href="/" class="navbar-brand"><%= image_tag 'logo_menu_x2.png' %></a>
      </div>
      <div class="col-sm-5">
        <ul class="nav nav-justified menu-links navbar-right">
          <%= render 'layouts/navigation_links_right' %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links_left.html.erb
<%# add navigation links to this file %>

<li><%= link_to 'úvod', page_path('home') %></li>
<li><%= link_to 'terassa', page_path('about') %></li>
<li><%= link_to 'menu', page_path('menu') %></li>

app/views/layouts/_navigation_links_right.html.erb
<%# add navigation links to this file %>

<li><%= link_to 'aktuálně'.html_safe, blog_index_path %></li>
<li><%= link_to 'galerie', page_path('photos') %></li>
<li><%= link_to 'kontakt', page_path('contact') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
  <head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Terassacafe" %></title>
    <meta name="description" content="Terassa cafe je restaurace, kavárna a bistro v Kralupech nad Vltavou. Nabízí vždy jídla z čerstvých surovin a je zaručena vždy jejich maximální kvalita.">
    <meta name="keywords" content="restaurace, cafe, kafe, Kralupy nad Vltavou, káva, kavárna, jídlo Kralupy nad Vltavou">
    <meta name="author" content="Adam Plánský">
    <meta name="robots" content="all">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
    <%= favicon_link_tag '/favicon.ico' %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
   <%= render 'layouts/footer' %>

 <script>
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

   ga('create', 'UA-55332146-3', 'auto');
   ga('send', 'pageview');

 </script>
  </body>





</html>

app/views/pages/about.html.erb
<% content_for :title do %>
Terassa cafe
<% end %>

<div class="container">

  <div class="starter-template">
 
    <div class="test about" >
      <h1>
        <span>Terassa</span>
      </h1>
      
      <div>
        <h2 class="h2">Možnosti na TERASSE</h2>
        <h3>Retro večer</h3>
        <p>Ať už si představujete jen malou rodinnou oslavu, nebo chcete pozvat všechny přátele, počítejte s námi. Po domluvě pro vás rádi připravíme tematickou oslavu v retro stylu, gurmánskou ochutnávku nebo koktejlový večírek. A pokud zrovna nechcete přijít s vlastní společností, sledujte pravidelně náš facebook nebo webové stránky. Pravidelně pořádáme tematické večery, na kterých vás rádi přivítáme. </p>
        <h3>Co bude dnes k večeři?</h3>
        <p>Také vám připadá, že vaříte stále dokola ty samé recepty? Přijďte si pro inspiraci k nám. Každý den máme něco nového a něco osvědčeného. Tradiční recepty s moderním šarmem, které vás jistě osloví. Vaříte pro děti a víte, co nejí? Zavolejte a večeři upravenou speciálně pro ně si vyzvedněte cestou z práce. Potěšte partnera teplou večeří bez času stráveného v kuchyni. Pohodový večer si u nás můžete vyzvednout v krabičce.</p>
        <h3>Kancelář na TERASSE</h3>
        <p>Přijďte k nám vyměnit vyčerpávající stereotyp vašeho pracovního prostředí za inspirativní pauzu s voňavou kávou. U nás ji podáváme vždy s úsměvem. Na TERASSE načerpáte novou inspiraci, která při home office často mizí v nedohlednu. Nebo jen preferujete čerstvý vzduch před hučící klimatizací a z blikajících žárovek už vás pálí oči? U nás jsou vítáni všichni umělci, žurnalisté, právníci, i soukromí učitelé. Přijďte k nám a poznáte skutečnou výhodu své volné pracovní doby.</p>
        <h3>To go</h3>
        <p>Nestíháte, ale přesto se nechcete vzdát zdravého domácího jídla a lahodné kávy? Nebo jen nemáte chuť trávit čas v restauraci a raději večeříte v pohodlí domova? I to je u nás možné. Veškeré jídlo i nápoje vám zabalíme, nalijeme do kelímku nebo zkrátka upravíme tak, abyste si je mohli vzít s sebou. Ať už jsme jen zastávkou na cestě do práce, nebo plánujete celodenní výlet. </p>
        <h3>Bussines prochází žaludkem</h3>
        <p>Máte důležité obchodní jednání, u kterého záleží na každém detailu? Ať už jste jen dva nebo vás přijde víc, u nás nic není problém. V příjemné neformální atmosféře snadno najdete společnou řeč. Samozřejmostí je připojení Wi-Fi. Stihnout dvě věci najednou už dávno není nemožné. Obchodní schůzka a dobré jídlo tak bez problémů splynou v jeden příjemný zážitek.</p>
            <p>Zavřeli Vám v bance před nosem? Nebo máte po polední pauze ještě spoustu práce  a potřebujete doplnit energii? Zajděte k nám zapomenout na každodenní starosti, nebo na chvilku vypnout a vychutnat si šálek pohody ve všedním dni. Milá obsluha Vám každopádně zvedne náladu a dobré jídlo zase hladinu endorfinů. Jednoduše, s chvilkou u nás může být i pracovní den zábava. </p>
        <h3>Následník vychovaných rodičů je u nás milý host</h3>
    <p>Děti máme rádi, a proto jsme pro ně připravili i nějakou tu zábavu navíc. Vítáme u nás všechny maminky na mateřské dovolené, hlídací babičky i tatínky a jejich princezny. Nevyžadujeme absolutní klid, ale věříme, že kultivované prostředí TERASSY se stane vhodným místem k vysvětlení pojmů gentleman a malá dáma.</p>
        <h3>Na co máte chuť?</h3>
        <p>Vzpomínáte na chutě svého dětství, nebo plánujete rodinnou oslavu a přemýšlíte o občerstvení? Pro nás není problém uvařit téměř cokoli. Ať už zatoužíte po bramborových šiškách, plném hrnci guláše, tácech s jednohubkami nebo obložených mísách. Stačí zavolat nebo se stavit na kus řeči.</p>
        <h3>Snídaně do postele</h3>
        <p>Chcete překvapit někoho blízkého, potěšit nadřízené nebo si zkrátka jen zpříjemnit nedělní ráno? Zavolejte, a za chvilku může být teplá snídaně u vás. A samozřejmě nejenom snídaně. Od svačiny po večeři vám dovezeme jakékoli jídlo domů nebo do práce, pro vás a všechny, kdo nemají čas nebo chuť k nám zaskočit. Dobře se najíst už nemůže být snadnější. </p>
      </div>
      
     <h2 class="logo_down">
          <span><span></span></span>
      </h2>
      
	   
    
    
    
  </div>
</div>

app/views/pages/contact.html.erb
<% content_for :title do %>Kontakt<% end %>

<div class="container">

  <div class="starter-template">
   
    <div class="test contact" >
      <h1>
        <span>Kontakt</span>
      </h1>
      
      <section>
        <section class="pull-left col-xs-12 col-sm-6">
          <h3>TERASSA CAFE BISTRO</h3>
          <p>Palackého náměstí 1092<br>278 01 Kralupy nad Vltavou</p>
          <p>Terrassa cafe bistro se nachází v budově OD Perla vpravo od vstupu do prodejny Global.</p>
           <h3>OTEVÍRACÍ DOBA</h3>
           <p>PO - ČT: 9:00 - 21:00<br>
            PÁ-SO: 12:00 - 22:00<br>
             NE: zavřeno<br>
             <i style="font-size:12px">od 22.3.2015 bude otevřeno i v neděli</i><br>
             <strong>PÁ a SO: zavírací doba podle zájmu hostů</strong>
</p>
           
            <h3>REZERVACE</h3>
            <p>T: 723 974 105 <i style="font-size:12px">(rezervace)</i></p>
            <p>T: 733 788 843 <i style="font-size:12px">(objednávky rautů a hostin na míru)</i></p>
            <p>(volejte či pište, obratem odpovíme)</p>
            <p>E: <a href="mailto:terassacafe@seznam.cz">terassacafe@seznam.cz</a> </p>
        </section>
        <section class="pull-right col-xs-12 col-sm-6">
          <%= link_to image_tag("terassa_mapa.png"), image_path("terassa_mapa.png"), class: "thumbnail group2" %>
          
          <p class="ta-r">Zobrazit na <%= link_to "maps.google.com", "http://bit.ly/1E7biqe" %>
            
          <h3>FACEBOOK</h3>

          <p><%= link_to image_tag("icon_fb_bila@2x.png", width:'42', class:"pull-left fb-icon", style:"margin-right:5px"), "https://www.facebook.com/terassacafebistro"  %>Sledujte aktuální dění a neodolatelné denní nabídky na <%= link_to "Facebooku", "https://www.facebook.com/terassacafebistro"%> !</p>
        </section>
      </section>
      <h2 class="logo_down"><span><span></span></span></h2>
    </div>
  </div>
</div>

<script type="text/javascript" >
 $(document).ready(function(){
   $(".group2").colorbox({rel:'group2',maxWidth:'95%',		maxHeight:'95%'});
 });
</script>

app/views/pages/home.html.erb
<% content_for :title do %>Úvod<% end %>

<div class="container">

  <div class="starter-template">
     
        
        
    <div class="details">
      <div class="outerCircle">
        <div class="circle"> 
          <h1>Protože  „jídlo sbližuje“</h1>
        </div>
      
        <div class="circle2">
        
    
          <span class="heading">TERASSA café</span>
         
          <p>Dávno už není zvykem běhat jen mezi domovem a prací, správné je vychutnat si každou minutu.</p>
          <p>A proto jsme tady my, bistro s francouzským šarmem a domácími ingrediencemi. Stavte se u nás na tradiční poctivé jídlo v moderním kabátě nebo ochutnejte jednu z našich lehkých delikates. A to není všechno. Připravujeme pro vás čerstvé domácí limonády, voňavou kávu i zákusky pro mlsné jazýčky. Vínem od pečlivě vybraných tuzemských vinařů si u nás zpříjemníte večer a ráno vás přiláká vůně teplé snídaně. To vše v příjemném, nekonvenčním a nekuřáckém prostředí, kde JÍDLO SBLIŽUJE.</p>		
          <a href="/pages/about" class="button">více...</a>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/pages/menu.html.erb
<% content_for :title do %>Menu<% end %>

<div class="container">

  <div class="starter-template">
   
    <div class="test menu" >
      <h1>
        <span>MENU</span>
      </h1>
      
      <section>
        <section class="col-xs-12 col-sm-12 ta-c">
          <p>Prohlédněte si naší stálou nabídku na nápojovém a jídelním lístku.</p>
          <section>
          <section class="menu_in">
            <%= link_to (image_tag "icon_snidane@2x.png", width:"50"),"/snidane.pdf" %>
            <%= link_to (image_tag "icon_napojovy_listek@2x.png", width:"50"), "/napojovy_listek.pdf" %>
            <%= link_to (image_tag "icon_jidelni_listek@2x.png", width:"50"),"/jidelni_listek.pdf" %>
          </section>
        </section>
          <p>
            Protože na Terasse vaříme z nejčerstvějších surovin a několikrát denně vás překvapíme čerstvými nápady z naší kuchyně, sledujte aktuální nabídku na <%= link_to "facebooku", "https://www.facebook.com/terassacafebistro"%>. A i tak vždy na Terasse najdete ještě něco navíc.
            
          </p>
        </section>
      </section>

      
      
      
      <h2 class="logo_down"><span><span></span></span></h2>
    </div>
  </div>
</div>

app/views/pages/photos.html.erb
<% content_for :title do %>Fotky<% end %>

<div class="container">

  <div class="starter-template">
    
    <div class="row">
      <h1>
        <span>Galerie</span>
      </h1>
   
      

        <div class="col-sm-6 col-md-4">
          <%= link_to image_tag("photos/s1.jpg"), image_path("photos/1.jpg"), class:"thumbnail group1" %>
        </div>

        <div class="col-sm-6 col-md-4">
          <%= link_to image_tag("photos/s2.jpg"), image_path("photos/2.jpg"), class:"thumbnail group1"  %>
        </div>

        <div class="col-sm-6 col-md-4">
            <%= link_to image_tag("photos/s3.jpg"), image_path("photos/3.jpg"), class:"thumbnail group1"  %>
        </div>


        <div class="col-sm-6 col-md-4">
          <%= link_to image_tag("photos/s4.jpg"), image_path("photos/4.jpg"), class:"thumbnail group1" %>
        </div>

        <div class="col-sm-6 col-md-4">
          <%= link_to image_tag("photos/s5.jpg"), image_path("photos/5.jpg"), class:"thumbnail group1"  %>
        </div>

        <div class="col-sm-6 col-md-4">
            <%= link_to image_tag("photos/s6.jpg"), image_path("photos/6.jpg"), class:"thumbnail group1"  %>
        </div>


        <div class="col-sm-6 col-md-4">
          <%= link_to image_tag("photos/s7.jpg"), image_path("photos/7.jpg"), class:"thumbnail group1" %>
        </div>

        <div class="col-sm-6 col-md-4">
          <%= link_to image_tag("photos/s8.jpg"), image_path("photos/8.jpg"), class:"thumbnail group1"  %>
        </div>

        <div class="col-sm-6 col-md-4">
            <%= link_to image_tag("photos/s9.jpg"), image_path("photos/9.jpg"), class:"thumbnail group1"  %>
        </div>
      
        <div class="col-sm-6 col-md-4">
          <%= link_to image_tag("photos/s10.jpg"), image_path("photos/10.jpg"), class:"thumbnail group1" %>
        </div>

        <div class="col-sm-6 col-md-4">
          <%= link_to image_tag("photos/s11.jpg"), image_path("photos/11.jpg"), class:"thumbnail group1"  %>
        </div>

        <div class="col-sm-6 col-md-4">
            <%= link_to image_tag("photos/s12.jpg"), image_path("photos/12.jpg"), class:"thumbnail group1"  %>
        </div>
        
   
          <div class="col-sm-6 col-md-4">
            <%= link_to image_tag("photos/s13.jpg"), image_path("photos/13.jpg"), class:"thumbnail group1" %>
          </div>

          <div class="col-sm-6 col-md-4">
            <%= link_to image_tag("photos/s14.jpg"), image_path("photos/14.jpg"), class:"thumbnail group1"  %>
          </div>

          <div class="col-sm-6 col-md-4">
              <%= link_to image_tag("photos/s15.jpg"), image_path("photos/15.jpg"), class:"thumbnail group1"  %>
          </div>
    
        
     
        
        
        
      
    </div>
  </div>

</div>

<script type="text/javascript" >



 $(document).ready(function(){
   $(".group1").colorbox({rel:'group1',maxWidth:'95%',		maxHeight:'95%'});
 });
</script>